eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:7777/eureka/
server:
 port: 7778
spring:
 application:
  name: gateway
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jb_crm_team?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 1024
 redis:
  host: localhost
  port: 6379
  pool:
   max-active: 10
 rabbitmq:
  host: localhost
  port: 5572
  username: guest
  password: guest
management:
 security:
  enabled: false
zuul:
 routes:
  user-service:
   path: /api/**
   serviceId: user-service
  sale-service:
     path: /api2/**
     serviceId: sale-service