eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:7777/eureka/
server:
 port: 7702
spring:
 application:
  name: sale-service
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jb_crm_team?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 1024
 redis:
   host: localhost
   port: 6379
   pool:
     max-active: 10